spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 1000
            read-timeout: 1000
            loggerLevel: FULL
            retryer: feign.Retryer.Default
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      eager: true
# 开启sentinel
feign:
  sentinel:
    enabled: true
#          service-product:
#            connectTimeout: 3000
#            read-timeout: 5000
#            loggerLevel: FULL