server:
  port: 8000

spring:
  profiles:
    active: dev
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: ${spring.profiles.active:}
logging:
  level:
    com.su.order.feign: debug

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - nacos:database.yaml?group=order
      - nacos:common.yaml?group=order
---
spring:
  config:
    activate:
      on-profile: test
    import:
      - nacos:database.yaml?group=order
      - nacos:common.yaml?group=order
      - nacos:test.yaml?group=order
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - nacos:database.yaml?group=order
      - nacos:common.yaml?group=order
      - nacos:prod.yaml?group=order