 service {
   #默认事务服务组映射
   vgroupMapping.default_tx_group = "default"
   #默认注册中心地址
   default.grouplist = "127.0.0.1:8091"
   #启动降级，当前不支持
   enableDegrade = false
   #禁用全局事务
   disableGlobalTransaction = false
 }